SIM ?= verilator
TOPLEVEL_LANG := verilog

PROJECT_ROOT := $(abspath \
	$(dir $(lastword $(MAKEFILE_LIST)))/..)

FIFO_DEPTH ?= 16

VERILOG_SOURCES := \
	$(PROJECT_ROOT)/rtl/async_fifo_gray.sv

TOPLEVEL := async_fifo_gray
COCOTB_TEST_MODULES := test_async_fifo

COMPILE_ARGS += --timing
COMPILE_ARGS += -Wall
COMPILE_ARGS += -Wno-fatal
COMPILE_ARGS += -GDEPTH=$(FIFO_DEPTH)

SIM_BUILD := \
	$(PROJECT_ROOT)/build/s5_fifo_$(FIFO_DEPTH)

COCOTB_RESULTS_FILE := \
	$(PROJECT_ROOT)/results/s5_fifo_$(FIFO_DEPTH).xml

export FIFO_DEPTH
export PYTHONPATH := \
	$(PROJECT_ROOT):$(PROJECT_ROOT)/tb:$(PYTHONPATH)

include $(shell cocotb-config --makefiles)/Makefile.sim
